### ISSUE TITLE
Can you provide a solution for SSG?

### ISSUE THREAD

**Issue by beratkara** [avitran0/deadlocked#1]
Will we be able to see features like hitting walls with SSG that we have seen in other cheats in this project?

**Comment by avitran0** [comment]
what exactly do you mean? like temporarily disabling the visibility check when holding an ssg?

**Comment by beratkara** [comment]
https://www.youtube.com/watch?v=HoNdTqmqh8Y

**Comment by avitran0** [comment]
absolutely not, for multiple reasons:

1. this is an external, and i cannot do raycasts like internals do to check for wallbangs easily.
2. this would require me to hook the CreateMove function, which directly writes to your viewangles, which again, i cannot do, because this is an external.
3. i don't do memory writes _at all_, because i don't want this to be detected.
4. this is not a rage cheat, and even the aimlock does not work 100% reliably, because again, this is an external, which writes to the mouse device file.
